// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/get-account-status.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("A Supabase publishable/anon key is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-account-status.ts
var get_account_status_default = defineTool({
  name: "get_account_status",
  title: "Get account status",
  description: "Return the signed-in AirMileX user's remaining credits, selected maps provider, and whether their Airtable and maps keys are configured.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_settings_flags", {
      p_user_id: ctx.getUserId()
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const row = data?.[0];
    if (!row) {
      return { content: [{ type: "text", text: "No settings found for this account yet." }] };
    }
    const status = {
      credits: row.credits,
      maps_provider: row.maps_provider,
      airtable_connected: row.has_pat,
      maps_key_configured: row.has_maps_key
    };
    return {
      content: [{ type: "text", text: JSON.stringify(status, null, 2) }],
      structuredContent: status
    };
  }
});

// src/lib/mcp/tools/list-calculation-logs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";
var list_calculation_logs_default = defineTool2({
  name: "list_calculation_logs",
  title: "List mileage jobs",
  description: "List the signed-in user's recent mileage calculation jobs, newest first, with the Airtable base and table, record count, and provider used.",
  inputSchema: {
    limit: z.number().int().optional().describe("How many jobs to return (1-100, default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(Math.trunc(limit ?? 20), 1), 100);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("calculation_logs").select("id, base_id, table_id, records_processed, provider_used, created_at").order("created_at", { ascending: false }).limit(take);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const jobs = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(jobs, null, 2) }],
      structuredContent: { jobs, count: jobs.length }
    };
  }
});

// src/lib/mcp/tools/list-saved-mappings.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
var list_saved_mappings_default = defineTool3({
  name: "list_saved_mappings",
  title: "List saved column mappings",
  description: "List the signed-in user's saved Airtable column mappings (start address, end address, and distance output column per table).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("saved_mappings").select("id, table_id, start_col_id, end_col_id, distance_col_id");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const mappings = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(mappings, null, 2) }],
      structuredContent: { mappings, count: mappings.length }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lumfnuyzdyzpokcxykvn";
var mcp_default = defineMcp({
  name: "airmilex",
  title: "AirMileX",
  version: "0.1.0",
  instructions: "Tools for AirMileX, an Airtable mileage calculator. Use `get_account_status` for remaining credits and connection status, `list_calculation_logs` for recent mileage jobs, and `list_saved_mappings` for saved Airtable column mappings.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_account_status_default, list_calculation_logs_default, list_saved_mappings_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
